const videosFree = [
    ['videos/HOOD NARUTO  pt.3 (full video) naruto vs sasuke.mp4', 38, 26],
    ['videos/HOOD NARUTO  pt.3 (full video) naruto vs sasuke.mp4', 46, 25],
    // ['videos/HOOD NARUTO  pt.4 (full video) naruto vs pain.mp4', 23, 32],
    'videos/[Re-upload] [1080p] HONK HONK.mp4',
    'videos/U GOT Яйца.mp4',
    ['videos/dj-eban2.mp4', 0, 30],
    ['videos/Пузантос - Бумаги [Morrowind].mp4', 129],
    'videos/06.mp4',
    'videos/16.mp4',

    ['videos/streamers/liz0N - Пятница (песенка про Minecraft).mp4', 31, 32],
    'videos/streamers/faker.mp4',
    'videos/streamers/grafon.mp4',
    'videos/streamers/mel.mp4',
    'videos/streamers/nam.mp4',

    'videos/A4.mp4',
    'videos/azamat.mp4',
    'videos/bebra.mp4',
    'videos/billy.mp4',
    'videos/bukin.mp4',
    'videos/ching.mp4',
    'videos/ebalo.mp4',
    'videos/gavno.mp4',
    'videos/kasino.mp4',
    'videos/krike.mp4',
    'videos/maestro.mp4',
    'videos/kal.mp4',
    'videos/zemo.mp4',
    'videos/karta.mp4',
    'videos/kid-hitmanclub.mp4',
    'videos/turboremix.mp4',
    'videos/SURA MURA - Симпл димпл нет поп ит.mp4',
    'videos/riba.mp4',
    'videos/mel pops.mp4',
    'videos/petecat.mp4',
    'videos/palich.mp4',
    'videos/кис-кис кис-кис, барака Обама, я Гордон ты Гордон, кис-кис кис-кис.mp4',
    'videos/Бегу по качалке, в голове. (♂Right version).mp4',
    'videos/Квас Закамский это хит.mp4',
    'videos/Моршу RTX - Ремикс_Morshu Remix.mp4',
    'videos/ОЙ - ОЙ НРАВИТСЯ.mp4',
    'videos/цiногриз!.mp4',
];